### ISSUE TITLE
function referenced in readme.md does not exist 

### ISSUE THREAD

**Issue by propyless** [juliengk/puppet-stdlibplus#2]
hi,
but the reference chapter of the readme.md for functions points to str2num. but there is no lib called str2num. but there is one for num2str.rb :)
num2str.rb

**Comment by juliengk** [comment]
Relax my friend! I haven't even tested the functions, just write it yesterday afternoon. Give it some time :) there is no rush!

**Comment by propyless** [comment]
ok =( i'm at home and was a bit bored so i thought i'd peer review  =P

**Comment by juliengk** [comment]
thanks for your comment, i will fix it :)
